name: Main, Develop branches semantic release
description: "Release based on main and develop branch"
author: Mehdi Rahimi <mehdirahimi.dev@gmail.com>
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latestTag
      continue-on-error: true
      uses: oprypin/find-latest-tag@e1e0e606cc7e9ede25140a5a139b3a5a1b717ece
      with:
        repository: ${{ inputs.repository }}
        releases-only: true
        token: ${{inputs.token}}

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Generate next version
      id: nextVersion
      if: steps.latestTag.outcome == 'success'
      run: echo "version=$(${GITHUB_ACTION_PATH}/dist/version ${{ steps.extract_branch.outputs.branch }} ${{ steps.latestTag.outputs.tag }})" >> $GITHUB_OUTPUT
      shell: sh

    - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
      if: steps.extract_branch.outputs.branch == 'develop' && steps.latestTag.outcome == 'success'
      with:
        repo_token: ${{ inputs.token }}
        prerelease: true
        automatic_release_tag: v${{ steps.nextVersion.outputs.version }}
        title: "${{inputs.releaseTitle}} v${{ steps.nextVersion.outputs.version }}"

    - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
      if: steps.extract_branch.outputs.branch == 'main' && steps.latestTag.outcome == 'success'
      with:
        repo_token: "${{ inputs.token }}"
        prerelease: false
        automatic_release_tag: v${{ steps.nextVersion.outputs.version }}
        title: "${{inputs.releaseTitle}} v${{ steps.nextVersion.outputs.version }} false"

    # If there was any previous release ===============================================================

    - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
      if: steps.extract_branch.outputs.branch == 'main' && steps.latestTag.outcome != 'success'
      with:
        repo_token: "${{ inputs.token }}"
        prerelease: false
        automatic_release_tag: v0.1.0
        title: "${{inputs.releaseTitle}} v0.1.0"

    - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
      if: steps.extract_branch.outputs.branch == 'develop' && steps.latestTag.outcome != 'success'
      with:
        repo_token: ${{ inputs.token }}
        prerelease: true
        automatic_release_tag: v0.1.0
        title: "${{inputs.releaseTitle}} v0.1.0"

    # Event dispatching ------------------------------------------------------

    - name: Dispatch event for new version
      if: steps.nextVersion.outputs.version != ''
      uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.eventScope }}
        eventType: ${{ inputs.eventType }}-${{  }}
        client-payload: ${{ inputs.eventPayload }}

    - name: Dispatch event, fallback
      if: steps.nextVersion.outputs.version == ''
      uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.eventScope }}
        eventType: ${{ inputs.eventType }}-v0.1.0
        client-payload: ${{ inputs.eventPayload }}

inputs:
  repository:
    required: false
    description: Target repository
    default: ${{ github.repository }}

  releaseTitle:
    required: false
    default: Auto Release
    description: Release title

  token:
    required: true
    description: Github token for releasing

  eventType:
    required: false
    description: Event that will be dispatched
    default: ${{ github.repository.name }}

  eventScope:
    required: false
    description: The scope of event dispatch

  eventPayload:
    required: false
    description: JSON event payload witch will be sent to scope or repositories
    default: "{}"

outputs:
  releaseVersion:
    value: ${{ steps.nextVersion.outputs.version || '0.1.0' }}
    description: latest release version
